"""phase4a_performance_management

Revision ID: ac11bb532d6e
Revises: 8657fab5a6af
Create Date: 2026-09-08 05:37:15.813172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac11bb532d6e'
down_revision: Union[str, None] = 'ea32162b1ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_cycles',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='cyclestatus'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_reviews',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_SELF_ASSESSMENT', 'PENDING_MANAGER_REVIEW', 'PENDING_AI_RECOMMENDATION', 'PENDING_HR_APPROVAL', 'PENDING_MANAGEMENT_APPROVAL', 'COMPLETED', name='reviewstatus'), nullable=False),
    sa.Column('self_assessment', sa.Text(), nullable=True),
    sa.Column('manager_rating', sa.Integer(), nullable=True),
    sa.Column('manager_comments', sa.Text(), nullable=True),
    sa.Column('ai_recommended_action', sa.Enum('PROMOTION', 'SALARY_HIKE', 'TRAINING', 'NO_CHANGE', name='recommendedaction'), nullable=True),
    sa.Column('ai_recommended_hike_percent', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('hr_approved_by_id', sa.UUID(), nullable=True),
    sa.Column('hr_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('management_approved_by_id', sa.UUID(), nullable=True),
    sa.Column('management_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_decision_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['hr_approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['management_approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'employee_id', name='uq_review_cycle_employee')
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected the same recurring spurious NUMERIC->UUID
    # alter_column ops on every existing UUID column across the schema (SQLite-
    # reflection artifact, not a real change -- see prior migrations for the same
    # note). Removed manually. Won't occur when generating against real Postgres.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_reviews')
    op.drop_table('performance_cycles')
    # ### end Alembic commands ###
