"""phase3c_payroll

Revision ID: ea32162b1ab3
Revises: 365d99bcb6f4
Create Date: 2026-08-20 06:54:28.147953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea32162b1ab3'
down_revision: Union[str, None] = '365d99bcb6f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_config',
    sa.Column('pf_rate_percent', sa.Float(), nullable=False),
    sa.Column('pf_wage_ceiling', sa.Float(), nullable=False),
    sa.Column('esi_rate_percent', sa.Float(), nullable=False),
    sa.Column('esi_wage_threshold', sa.Float(), nullable=False),
    sa.Column('pt_state', sa.String(length=100), nullable=False),
    sa.Column('pt_amount', sa.Float(), nullable=False),
    sa.Column('overtime_rate_multiplier', sa.Float(), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_runs',
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'HR_APPROVED', 'FINANCE_APPROVED', 'PAID', name='payrollrunstatus'), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('hr_approved_by_id', sa.UUID(), nullable=True),
    sa.Column('hr_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finance_approved_by_id', sa.UUID(), nullable=True),
    sa.Column('finance_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finance_approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hr_approved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_year', 'period_month', name='uq_payroll_run_period')
    )
    op.create_table('payslips',
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('basic', sa.Float(), nullable=False),
    sa.Column('hra', sa.Float(), nullable=False),
    sa.Column('other_allowances', sa.Float(), nullable=False),
    sa.Column('overtime_amount', sa.Float(), nullable=False),
    sa.Column('bonus_amount', sa.Float(), nullable=False),
    sa.Column('gross_salary', sa.Float(), nullable=False),
    sa.Column('days_in_period', sa.Integer(), nullable=False),
    sa.Column('days_present', sa.Integer(), nullable=False),
    sa.Column('days_on_leave', sa.Integer(), nullable=False),
    sa.Column('days_lop', sa.Integer(), nullable=False),
    sa.Column('pf_deduction', sa.Float(), nullable=False),
    sa.Column('esi_deduction', sa.Float(), nullable=False),
    sa.Column('pt_deduction', sa.Float(), nullable=False),
    sa.Column('tds_amount', sa.Float(), nullable=False),
    sa.Column('net_salary', sa.Float(), nullable=False),
    sa.Column('pdf_storage_key', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', name='uq_payslip_run_employee')
    )
    op.create_table('salary_structures',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('basic', sa.Float(), nullable=False),
    sa.Column('hra', sa.Float(), nullable=False),
    sa.Column('other_allowances', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected the same recurring spurious NUMERIC->UUID
    # alter_column ops on every existing UUID column across the schema (SQLite-
    # reflection artifact, not a real change — see prior migrations for the same
    # note). Removed manually. Won't occur when generating against real Postgres.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_structures')
    op.drop_table('payslips')
    op.drop_table('payroll_runs')
    op.drop_table('payroll_config')
    # ### end Alembic commands ###
