"""phase2c_onboarding_password_change

Revision ID: 5ff417d7d5b8
Revises: 992dea6462d6
Create Date: 2026-07-28 06:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff417d7d5b8'
down_revision: Union[str, None] = '992dea6462d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected the same recurring spurious NUMERIC->UUID
    # alter_column ops on every existing UUID column across the schema (SQLite-
    # reflection artifact, not a real change — see prior migrations for the same
    # note). Removed manually. Won't occur when generating against real Postgres.
    #
    # server_default=false() added deliberately (autogenerate didn't propose one) so
    # this migration doesn't fail on a table that already has rows: without a
    # server-side default, adding a NOT NULL column to a non-empty table errors.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
