"""phase2_add_resume_text_cache

Revision ID: f3a51dbc6151
Revises: 498b896f98d3
Create Date: 2026-07-25 05:57:01.472346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a51dbc6151'
down_revision: Union[str, None] = '498b896f98d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('resume_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected spurious NUMERIC->UUID alter_column ops on
    # every existing UUID column (same SQLite-reflection artifact as the previous
    # migration — SQLite has no native UUID type). Removed manually.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'resume_text')
    # ### end Alembic commands ###
